const jsonServer= require('json-server');
const cors=require('cors');
const server = jsonServer.create();
const port = process.env.PORT||3002;
const path = require('path');
const router = jsonServer.router(path.join(__dirname, 'database.json'));
const middlewares = jsonServer.defaults();
server.use(cors());
server.use(router);
server.listen(port);